# Generated by Django 3.1.7 on 2021-04-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('components', models.CharField(max_length=250, verbose_name='Components')),
                ('about', models.TextField(verbose_name='About Beer')),
                ('date', models.DateTimeField(verbose_name='date of publication')),
            ],
        ),
    ]
