version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  migration:
    image: migration
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - D:\dbdata:/app/database